name: Scan Python Code using Bandit

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Github Repo
        uses: actions/checkout@v3

      - name: python bandit
        run: |
            pip install bandit
            bandit -r .

   